[package]
name = "rhost"
version = "0.1.0"
description = "Cross-platform High-performance Remote Host Manager"
license = "MIT"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rhost_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.0", features = [] }
tauri-plugin-opener = "2"
russh = "0.63.3"
russh-sftp = "3.0.1"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "sync", "time", "io-util", "fs"] }
tokio-util = "0.7.19"
uuid = { version = "1.26.1", features = ["v4"] }
bytes = "1.12.1"
thiserror = "2.0.21"
keyring = "3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
sysinfo = "0.38.4"
libc = "0.2"
tauri-plugin-clipboard-manager = "2.4.1"
font-kit = "0.14"
